[package]
name = "firewall_plugin"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
wasi = "0.11.0+wasi-snapshot-preview1"  # Optional but useful

[profile.release]
opt-level = "z"
lto = true
strip = true
